-- INSERT INTO cliente(nome, email, senha, endereco, tipo_usuario, entidade_empregadora, tipo_cliente)
-- VALUES ('João', 'joao@email.com', '123456', 'Rua X', 'CLIENTE', 'Empresa Y', '0');
--
-- INSERT INTO agente(nome, email, senha, tipo_usuario)
-- VALUES ('Raphael Sena', 'rsenares1@gmail.com', '123456', 'AGENTE');
